// src/routes/contact.svelte
<script lang='ts'>
  import Social from './social.svelte'

  interface SocialData {
    name: string,
    icon: string,
    iconColor: string,
    handle: string
    url: string,
  }

  const socials: SocialData[] = [
    {
      name: 'Email',
      icon: 'carbon:email',
      iconColor: 'black',
      handle: 'wrdufault@outlook.com',
      url: 'mailto:wrdufault@outlook.com?subject=Hey%20Will%20👋'
    },
    {
      name: 'Linkedin',
      icon: 'simple-icons:linkedin',
      iconColor: '#3367bf',
      handle: 'willdufault',
      url: 'https://www.linkedin.com/in/willdufault'
    },
    {
      name: 'GitHub',
      icon: 'bi:github',
      iconColor: '#202328',
      handle: 'willdufault',
      url: 'https://github.com/willdufault'
    },
    {
      name: 'Upwork',
      icon: 'simple-icons:upwork',
      iconColor: '#46a614',
      handle: 'Will Dufault',
      url: 'https://www.upwork.com/freelancers/~0176292ee3fa699089'
    }
  ];
</script>
<main id='contact'>
  <h2>Contact</h2>
  <div class='container'>
    {#each socials as social}
      <Social name={social.name} icon={social.icon} iconColor={social.iconColor} handle={social.handle} url={social.url}></Social>
    {/each}
  </div>
</main>
<style>
  .container {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    grid-template-rows: repeat(2, 1fr);
    row-gap: 1.5rem;
  }
</style>

// src/sections/Contact.tsx
import type { Social } from "../types/Social"

export default function Contact() {
  const socials: Social[] = [
    {
      name: "Email",
      text: "hello@willdufault.dev",
      url: "mailto:hello@willdufault.dev",
    },
    {
      name: "GitHub",
      text: "willdufault",
      url: "https://github.com/willdufault",
    },
    {
      name: "LinkedIn",
      text: "willdufault",
      url: "https://www.linkedin.com.in/willdufault",
    },
    {
      name: "Resume",
      text: "View →",
      url: "/Will Dufault Resume.pdf",
    },
  ]

  return (
    <>
      <h2>Contact</h2>
      {socials.map((social) => (
        <div key={social.name}>
          {social.name}:&nbsp;
          <a
            href={social.url}
            className="text-neutral-400 underline hover:text-white"
          >
            {social.text}
          </a>
        </div>
      ))}
    </>
  )
}
