// src/routes/experience.svelte
<script lang="ts">
  interface Job {
    title: string,
    company: string,
    logoPath: string,
    logoAlternateText: string,
    bullets: string[],
    startDate: string,
    endDate: string
  }

  const jobs: Job[] = [
    {
      title: 'Software Engineer Intern',
      company: 'BJ\'s Wholesale Club',
      logoPath: './images/bjs-logo.jpg',
      logoAlternateText: 'BJ\'s Wholesale Club logo',
      bullets: [
        'Earned the Pacesetter Award for ranking in the top 20% of interns',
        'Saved $5,800/year through automation using Python, Jenkins, Docker, and AWS'
      ],
      startDate: 'May 2023',
      endDate: 'Present'
    },
    {
      title: 'Undergraduate TA',
      company: 'WPI',
      logoPath: './images/wpi-goat-logo.jpg',
      logoAlternateText: 'WPI goat logo',
      bullets: [
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, quasi?',
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, quasi?'
      ],
      startDate: 'Sep 2023',
      endDate: 'Dec 2023'
    },
    {
      title: 'Paint Sales Associate',
      company: 'The Home Depot',
      logoPath: './images/home-depot-logo.jpg',
      logoAlternateText: 'The Home Depot logo',
      bullets: [
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, quasi?',
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, quasi?'
      ],
      startDate: 'May 2022',
      endDate: 'Oct 2022'
    }
  ];
</script>
<main>
  <h2>Experience</h2>
  {#each jobs as job, index}
    {#if index > 0}
      <hr>
    {/if}
    <div class='container'>
      <img class='round' src={job.logoPath} alt='BJ&apos;s Wholesale Club logo'>
      <div class='text-wrapper'>
        <h4>{job.title}</h4>
        <p>{job.company}</p>
        <ul>
          {#each job.bullets as bullet}
            <li>{bullet}</li>
          {/each}
        </ul>
        <p class='subtext'>{job.startDate} &rarr; {job.endDate}</p>
      </div>
    </div>
  {/each}
</main>
<style>
  .container {
    display: flex;
    align-items: flex-start;
    gap: 1.2rem;
  }

  img {
    max-width: 6rem;
  }
</style>

// src/components/Experience/index.tsx
import bjsLogo from '../../assets/images/bjs-logo.webp'

import wpiSeal from '../../assets/images/wpi-seal.webp'
import Card from '../Card'
import Tags from '../Tags'
import type { Job, Role } from './types'

function Experience() {
  const jobs: Job[] = [
    {
      company: "BJ's Wholesale Club",
      roles: [
        {
          title: 'Cloud Software Engineer',
          start: 'Aug 2024',
          end: 'Now',
        },
        {
          title: 'Cloud Software Engineer Intern',
          start: 'May 2023',
          end: 'Aug 2024',
        },
      ],
      skills: ['Python', 'AWS', 'DynamoDB', 'Jenkins', 'Docker'],
      logo: bjsLogo,
      alt: "Bj's Wholesale Club logo",
    },
    {
      company: 'WPI',
      roles: [
        {
          title: 'Undergraduate Teaching Assistant',
          start: 'Sep 2023',
          end: 'Dec 2023',
        },
      ],
      skills: ['Java', 'Python'],
      logo: wpiSeal,
      alt: 'WPI seal',
    },
  ]
  return (
    <section>
      <h1 className="font-bold text-2xl mb-4">Experience</h1>
      <div className="flex flex-col gap-2">
        {jobs.map((job: Job, jobIndex: number) => (
          <Card key={jobIndex}>
            <div className="flex flex-col sm:flex-row gap-4">
              <img
                src={job.logo}
                alt={job.alt}
                className="w-24 h-24 rounded-md"
              />
              <div>
                <h2 className="font-bold">{job.company}</h2>
                <div className="mb-4 flex flex-col gap-2">
                  {job.roles.map((role: Role, roleIndex: number) => (
                    <div key={roleIndex}>
                      <h3>{role.title}</h3>
                      <p className="text-sm text-neutral-400">
                        {role.start} &rarr; {role.end}
                      </p>
                    </div>
                  ))}
                </div>
                <Tags items={job.skills} />
              </div>
            </div>
          </Card>
        ))}
      </div>
    </section>
  )
}

export default Experience
